image: pickoba/gitpod-satysfi:0.0.6

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - pickoba.satysfi-workshop
    - tomoki1207.pdf

tasks:
  - before: |
      opam install -y satysfi-easytable
      satyrographos install
    command: |
      satysfi demo/demo.saty
      open demo/demo.saty
